### PR TITLE
Swap dependency tracking source

### PR DESCRIPTION
**Pull request by afgane**
Followup to #182 (and issue #186) swapping out use of submodules for dependent roles to using `ansible-galaxy` command: `ansible-galaxy install -r requirements_roles.yml -p roles`. Installation docs still need updating plus see how Travis deals with the swap.

### CODE REVIEW

**Comment by afgane** [comment]
@mvdbeek @drosofff  It seems the `data_managers` role just installs a set of data managers tools and it doesn't do anything else. Couldn't we just have the list of data managers be provided as a tools list in the repo and omit that role? With the recent shift of ephemeris for the scripts, the role will need to significantly reworked?

**Comment by mvdbeek** [comment]
> With the recent changes to the galaxy-tools role and a shift of ephemeris for the scripts, the role will need to significantly reworked making it a second place to modify the shed_install script (and in the mean time it's failing).

Absolutely, that needs to happen. Feel free to remove the role, otherwise I can also do that.

**Comment by afgane** [comment]
This looks ready to go I believe. Let me know if you'd like to see something else updated with this migration.

**Comment by drosofff** [comment]
👍 Thanks @afgane

**Pull request merged**
