### PR TITLE
Use pypi ansible (currently at 2.1.2.0)

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by drosofff** [comment]
will the test pass if I merge the PR ?

**Comment by mvdbeek** [comment]
No, there is a whole chain of problems, but I'm on it.

**Comment by drosofff** [comment]
OK, thanks

**Comment by drosofff** [comment]
hurray 👍

**Comment by mvdbeek** [comment]
This was tricky, postgresql was refusing to start due to a permission problem that happens when you change the postgresql user id and subsequently you also adapt the file system permissions (`chown <new_user_id> <somefolder>`).
For some reason docker ignores this last chmod, so you have to backup the files in the folder, delete the folder and create a new folder and move the backuped files back.  So far so good, we knew that already. But how could it have worked in the past if we ran that command after the playbook?
It's a mystery, and I'm not happy about that :(.

**Comment by drosofff** [comment]
is it possible that travis upgrade somehow its docker layer ?

**Pull request merged**
