### PR TITLE
Metavisitor 2016 11 10

### PR DESCRIPTION
**Pull request by drosofff**
Almost done with Metavisitor Workflow updates

### CODE REVIEW

**Comment by drosofff** [comment]
The docker image https://hub.docker.com/r/artbio/metavisitor-1.2/ has been successfully tested and upgraded. I'll merge in few hours.

**Comment by mvdbeek** [comment]
If this is building in a reasonable amount of time we can also try again to let this be built by the dockerhub!

**Comment by drosofff** [comment]
Definitely <2h. I'll time this and let you know. If it fixes something that annoys me, I buy it:

Each time we upload the docker image metavisitor-1.2, we loose the previous one, right. Would not be possible to have a commit track ? Well, I know that the github repo _is_ this track, but it is not as easy for external users of the docker image.

**Comment by mvdbeek** [comment]
> Definitely <2h. I'll time this and let you know. If it fixes something that annoys me, I buy it:

We can just give it a shot (after merging), if it doesn't build, nothing bad happens.



> Each time we upload the docker image metavisitor-1.2, we loose the previous one, right. Would not be possible to have a commit track ? Well, I know that the github repo is this track, but it is not as easy for external users of the docker image.

You have to tag them with the commit hash, or the release number. Probably it's best to tag with the release number. (docker tag artbio/metavisitor-1.2:<commit_number>) and then push that as well (which will be fast, since the layers are the same)

**Comment by drosofff** [comment]
The docker build take 30 min !

**Comment by mvdbeek** [comment]
> The docker build take 30 min !

with most time spent on building trackster, I bet. but that's for the next PR ;).
Feel free to merge when ready.

**Comment by drosofff** [comment]
> with most time spent on building trackster

Mmm no. I would say ~20 min for installation of metavisitor tools (sra, blast and trinity are the winners)

**Comment by mvdbeek** [comment]
right, trackster should be just the base image.

**Comment by drosofff** [comment]
OK, before merging, artbio/metavisitor-1.2:16_11 is uploaded in docker hub

**Pull request merged**
