### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by drosofff**
implement galaxykickstart_from_workflow.py to create a Galaxy server flavor from .ga workflow file(s).
Running galaxykickstart_from_workflow.py from the script folder

- creates a new inventory file in inventory_files folder
- creates a "gks_workflows" file in group_vars folder
- creates a tool_list.yml file from galaxy workflow files and copy these files in an extra-files/gks_workflows folder

In addition, a scripts/galaxykickstart_from_workflow_templates folder contains the template files

- group_vars_template.yml
- tool_sheds_conf.xml.sample

### CODE REVIEW

**Comment by mvdbeek** [comment]
@drosofff you'll have to rebase this on top of the current master branch.

So while you're on this branch, fetch from the GalaxyKickstart remote (`git fetch origin`, I guess).
Then git rebase origin/master should do it. (This reverts all commits, and then plays them back on top of the current master branch)

**Comment by drosofff** [comment]
> So while you're on *this* branch

means the dev branch, right ?

**Comment by mvdbeek** [comment]
Yes

**Comment by drosofff** [comment]
Fix ansible-artimed to GalaxyKickStart before merge

**Pull request merged**
